name: Majsoul-Login
on:
  workflow_dispatch:
  schedule: #5:00
   - cron: '0 21 * * *'
jobs:
  login:
    name: Majsoul-Login
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Selenium
        run: pip install selenium==4.17.2

      - name: Majsoul login
        run: python login.py ${{ secrets.EMAIL }} ${{ secrets.PASSWD }}

      - name: Commit and push log file
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add log.txt
          git diff --staged --quiet || git commit -m "Auto update login log - $(date +'%Y-%m-%d %H:%M:%S')"
          git push
